export const npm = [
  { "key": "Express", "value": "Fast, minimalist Node.js web framework." },
  { "key": "Mongoose", "value": "MongoDB ODM for schema-based data modeling." },
  { "key": "Multer", "value": "Middleware for handling file uploads in Node.js." },
  { "key": "Cloudinary", "value": "Cloud storage for image and video management." },
  { "key": "CORS", "value": "Middleware for handling cross-origin requests." },
  { "key": "Dotenv", "value": "Loads environment variables from .env files." },
  { "key": "Arcjet", "value": "Serverless framework for APIs and automation." },
  { "key": "Node-cron", "value": "Scheduler for running cron jobs in Node.js." },
  { "key": "Moment.js", "value": "JavaScript library for date and time manipulation." },
  { "key": "Body-parser", "value": "Middleware for parsing incoming request bodies." },
  { "key": "Bootstrap", "value": "Popular CSS framework for responsive design." },
  { "key": "Puppeteer", "value": "Headless browser automation for web scraping." },
  { "key": "TanStack Query", "value": "Data fetching and caching for React apps." },
  { "key": "React Router DOM", "value": "Declarative routing for React applications." },
  { "key": "Toastify", "value": "Library for customizable notifications in React." },
  { "key": "React Icons", "value": "Collection of customizable icons for React." },
  { "key": "Chakra UI", "value": "Modern React UI component library." },
  { "key": "Tailwind CSS", "value": "Utility-first CSS framework for styling." },
  { "key": "React-pdf", "value": "Generate and display PDFs in React." },
  { "key": "JWT", "value": "Token-based authentication and authorization." },
  { "key": "Firebase Admin SDK", "value": "Manage Firebase services programmatically." },
  { "key": "Zustand", "value": "Simple, scalable state management for React." },
  { "key": "Preline", "value": "Component library for Tailwind-based design." },
  { "key": "ExcelJS", "value": "Read, write, and manipulate Excel files." },
  { "key": "ApexCharts", "value": "Interactive charting library for data visualization." },
  { "key": "Bcrypt", "value": "Secure password hashing for authentication." },
  { "key": "Nanoid", "value": "Lightweight, unique ID generator." },
  { "key": "Nodemailer", "value": "Send emails from Node.js applications." },
  { "key": "React-slick", "value": "Carousel slider component for React." },
  { "key": "GSAP", "value": "High-performance JavaScript animation library." },
  { "key": "Crypto", "value": "Node.js module for cryptographic operations." },
  { "key": "Redux", "value": "Predictable state management for JavaScript applications." }
]
