export const skills = [
  {
    id: "languages",
    title: "Languages",
    skills: [
      { name: "Python" },
      { name: "Java" },
      { name: "JavaScript" },
      { name: "TypeScript" },
    ],
  },
  {
    id: "databases",
    title: "Databases",
    skills: [{ name: "MySQL" }, { name: "MongoDB" }, { name: "PostgreSQL" }],
  },
  {
    id: "web-backend",
    title: "Web and Backend Development",
    skills: [
      { name: "HTML" },
      { name: "CSS" },
      { name: "React" },
      { name: "Next.js" },
      { name: "Redux" },
      { name: "RTK" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "FastAPI" },
      { name: "REST APIs" },
      { name: "Spring Boot" },
      { name: "Zustand" },
    ],
  },
  {
    id: "tools-platforms",
    title: "Tools and Platforms",
    skills: [
      { name: "Git" },
      { name: "VS Code" },
      { name: "IntelliJ IDEA" },
      { name: "pgAdmin" },
      { name: "Docker" },
      { name: "Redis" },
      { name: "Firebase" },
      { name: "Linux" },
      { name: "Drizzle ORM" },
      { name: "Bruno" },
    ],
  },
  {
    id: "core-cs",
    title: "Core Computer Science",
    skills: [
      { name: "Computer Networks" },
      { name: "Operating Systems" },
      { name: "Database Management Systems" },
      { name: "Object Oriented Programming" },
    ],
  },
  {
    id: "system-design",
    title: "System Design Concepts",
    skills: [
      { name: "Client-Server & System Architectures" },
      { name: "Monolithic vs Microservices" },
      { name: "Load Balancing (L4/L7, Algorithms)" },
      { name: "API Gateway (Routing, Auth, Rate Limiting)" },
      { name: "REST APIs & gRPC" },
      { name: "Indexing, Sharding & Partitioning" },
      { name: "SQL vs NoSQL Databases" },
      { name: "Transactions, ACID & CAP Theorem" },
      { name: "Caching & CDN" },
      { name: "Message Brokers & Event-driven Architecture" },
      { name: "Database Normalization & Denormalization" },
      { name: "Security (XSS, SQLi, CSRF, Basics)" },
      { name: "Messaging Queues & Asynchronous Processing" },
      { name: "Sockets & WebSockets" },
      { name: "Web Servers (Nginx, Apache) & Proxies" },
      { name: "Stateful vs Stateless Systems" },
      { name: "Synchronous vs Asynchronous Communication" },
      { name: "Rate Limiting & Firewalls" },
      { name: "System Metrics (Latency, Throughput, Errors)" },
    ],
  },
];
